---
  - name: Set facts for ecs cluster
    set_fact:
      ecs_cluster_name: "{{ app_name }}-ecs"
  - name: Create "{{ app_name }}" cluster
    ecs_cluster:
      name: "{{ ecs_cluster_name }}"
      state: present
