---
subnets: [
    {cidr: 172.24.0.0/24, region: us-east-2, az: us-east-2a},
    {cidr: 172.24.1.0/24, region: us-east-2, az: us-east-2b}]
app_name: "notejam-prod"
vpc_net: 172.24.0.0/16
backup_retention: 7
instance_type: t2.micro
container_memory: 400
ami_ecs_optimized: ami-b86a5ddd
aws_account_id: "{{ lookup('env', 'AWS_ACCOUNT_ID') }}"
aws_region: "{{ lookup('env', 'AWS_REGION') }}"
# look https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-access-logs.html#attach-bucket-policy
elb_access_ids: ["033677994240"]
pwd_alias: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
size: 2
key_dest: "~/.ssh/notejam-private.pem"
