---
subnets: [
    {cidr: 172.23.0.0/24, region: us-east-2, az: us-east-2a},
    {cidr: 172.23.1.0/24, region: us-east-2, az: us-east-2b}]
app_name: "notejam-staging"
vpc_net: 172.23.0.0/16
backup_retention: 1
instance_type: t2.micro
container_memory: 400
ami_ecs_optimized: ami-b86a5ddd
aws_account_id: "{{ lookup('env', 'AWS_ACCOUNT_ID') }}"
aws_region: "{{ lookup('env', 'AWS_REGION') }}"
# look https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-access-logs.html#attach-bucket-policy
elb_access_ids: ["033677994240"]
pwd_alias: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
size: 1
key_dest: "~/.ssh/notejam-private.pem"
lb_check_interval: 30
