---
  - name: Set facts for ecs cluster
    set_fact:
      ecs_cluster_name: "{{ app_name }}-ecs"
      ecs_service_name: "{{ app_name }}-svc"
  - name: Create "{{ app_name }}" cluster
    ecs_cluster:
      name: "{{ ecs_cluster_name }}"
      state: present
  - name: Create ecs task definition
    ecs_taskdefinition:
      family: notejam
      state: present
      containers:
      - name: notejam
        essential: true
        memory: 800
        image: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com/notejam:latest"
        portMappings:
        - containerPort: 8000
          hostPort: 80
  - name: Create notejam service
    ecs_service:
      name: "{{ ecs_service_name }}"
      state: present
      cluster: "{{ecs_cluster_name}}"
      desired_count: 2
      task_definition: notejam
      load_balancers: [
        {loadBalancerName: "{{ lb_name }}", containerName: notejam, containerPort: 8000 }
      ]
      role: "arn:aws:iam::{{ aws_account_id }}:role/aws-service-role/ecs.amazonaws.com/AWSServiceRoleForECS"



