---
  - name: "Create bucket {{ app_name }}-logs"
    aws_s3:
      bucket: "{{ app_name }}-logs"
      permission: private
      mode: create
  - name: "Add s3 bucket policy for lb"
    command: "aws s3api put-bucket-policy --bucket {{ app_name }}-logs --policy \'{{ lookup('template', 'lb_policy.json') | to_nice_json}}\'"
  - name: "Create security group for lb"
    ec2_group:
      name: "{{ app_name }}_public_http"
      vpc_id: "{{ vpc_id }}"
      description: "Group to use for public http access in {{ vpc_id }}"
      rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
    register: public_http_group
  - name: "Set fact with load balancer name {{ app_name}}-lb"
    set_fact:
      lb_name: "{{app_name}}-lb"
  - name: "Create lb configuration - {{ app_name }}"
    ec2_elb_lb:
      name: "{{ lb_name }}"
      state: present
      subnets: "{{ vpc_subnets_ids }}"
      security_group_ids: ["{{ public_http_group.group_id }}"]
      listeners:
        - protocol: http
          load_balancer_port: 80
          instance_port: 80
      health_check:
        ping_protocol: http
        ping_port: 80
        ping_path: "/status/ping"
        response_timeout: 5
        interval: 30
        unhealthy_threshold: 2
        healthy_threshold: 10
      access_logs:
        s3_location: "{{ app_name }}-logs"
        s3_prefix: "lb"

