---
  - name: Set initial facts
    set_fact:
      vpc_name: "{{ app_name }}-vpc"
  - name: Create VPC for staging
    ec2_vpc_net:
      name: "{{ vpc_name }}"
      state: present
      cidr_block: "{{ vpc_net }}"
      resource_tags: { "env": "{{ app_name }}" }
    register: vpc
  - name:               Set VPC ID in variable
    set_fact:
      vpc_id:           "{{ vpc.vpc.id }}"
  - name: "Create Subnet for {{ vpc_name }} - {{ item.az }}"
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{ vpc_id }}"
      cidr: "{{ item.cidr }}"
      region: "{{ item.region }}"
      az:  "{{ item.az }}"
      resource_tags:
        Name: "{{ vpc_name }}"
    with_items:
      "{{ subnets }}"
    register: web_subnet
  - name: "Gather facts about created vpc subnets"
    ec2_vpc_subnet_facts:
      filters:
        "tag:Name": "{{vpc_name}}"
    register: vpc_subnets
  - name: "Set vpc subnets ids fact"
    set_fact:
      vpc_subnets_ids: "{{ vpc_subnets.subnets |map(attribute='id') |list}}"
  - name: "Create VPC Internet Gateway for {{ vpc_name }}"
    ec2_vpc_igw:
      vpc_id: "{{ vpc_id }}"
      region: "{{ aws_region }}"
      state: "present"
    register: vpc_igw
  - name: "Set fact for {{ vpc_name }} igw ID"
    set_fact:
      igw_id: "{{ vpc_igw.gateway_id }}"
  - name: "Set public subnet routes for {{ vpc_name }}"
    ec2_vpc_route_table:
      vpc_id:           "{{ vpc_id }}"
      region:           "{{ aws_region }}"
      tags:
        Name:           "Public"
      subnets: "{{ vpc_subnets_ids }}"
      routes:
        - dest:         "0.0.0.0/0"
          gateway_id:   "{{ igw_id }}"
  - name: "Create security group for {{ vpc_name }}"
    ec2_group:
      name: "{{ app_name }}"
      vpc_id: "{{ vpc_id }}"
      description: "Group to use with {{ vpc_name }}"
      rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: "{{ vpc_net }}"
    register: web_group
