- hosts: localhost
  gather_facts: false
  vars:
    aws_cicd_username: "notejam_cicd"
    aws_account_id: "{{ lookup('env', 'AWS_ACCOUNT_ID') }}"
    aws_region: "{{ lookup('env', 'AWS_REGION') }}"
    elb_access_ids: ["033677994240"]
  tasks:
  - name: Create ECR repository
    ecs_ecr:
      name: notejam
  - name: Create role for codebuild
    iam_role:
      name: notejam-codebuild-role
      state: present
      assume_role_policy_document: |
        {
            "Version": "2008-10-17",
            "Statement": [
                {
                    "Action": "sts:AssumeRole",
                    "Principal": {
                        "Service": "codebuild.amazonaws.com"
                    },
                    "Effect": "Allow",
                    "Sid": "1"
                }
            ]
        }
      managed_policy:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
  - name: Create role for ecsInstance
    iam_role:
      name: ecsInstanceRole
      state: present
      assume_role_policy_document: |
        {
          "Version": "2008-10-17",
          "Statement": [
            {
              "Sid": "",
              "Effect": "Allow",
              "Principal": {
                "Service": "ec2.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        }
      managed_policy:
        - "arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role"
  - name: Grant permissions to logs for ecsInstanceRole
    iam_policy:
      iam_type: role
      iam_name: ecsInstanceRole
      policy_name: ecsInstanceRole-awslogs
      state: present
      policy_json: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "logs:CreateLogStream",
                "logs:PutLogEvents",
                "logs:CreateLogGroup"
            ],
              "Resource": [
                "arn:aws:logs:*:*:*"
            ]
          }
         ]
        }
  - name: Create service role for ecs
    command: "aws iam create-service-linked-role --aws-service-name ecs.amazonaws.com"
    ignore_errors: true

  - name: Grant permissions to notejam-codebuild-role
    iam_policy:
      iam_type: role
      iam_name: notejam-codebuild-role
      policy_name: notejam-codebuild-policy
      state: present
      policy_json: "{{ lookup( 'template', 'files/codebuild_policy.json') }}"
  - name: Create role for codepipeline
    iam_role:
      name: notejam-codepipeline-role
      state: present
      assume_role_policy_document: |
        {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Action": "sts:AssumeRole",
                    "Principal": {
                        "Service": "codepipeline.amazonaws.com"
                    },
                    "Effect": "Allow",
                    "Sid": ""
                }
            ]
        }
  - name: Grant permission to notejam-codepieline-role
    iam_policy:
      iam_type: role
      iam_name: notejam-codepipeline-role
      policy_name: notejam-codepipeline-policy
      state: present
      policy_document: files/codepipeline_policy.json
