- hosts: localhost
  gather_facts: false
  vars:
    ami_ecs_optimized: ami-b86a5ddd
    aws_account_id: "{{ lookup('env', 'AWS_ACCOUNT_ID') }}"
    aws_region: "{{ lookup('env', 'AWS_REGION') }}"
    # look https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-access-logs.html#attach-bucket-policy
    elb_access_ids: ["033677994240"]
    pwd_alias: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
  roles:
    - { role: logs }
    - { role: ec2_key, dest: "~/.ssh/notejam-private.pem" }
    - { role: vpc }
    - {
        role: lb,
        subnets: "{{ vpc_subnets_ids }}",
        elb_access_ids: "{{ elb_access_ids }}"
      }
    - { role: database }
    - { role: ecs_cluster }
    - { role: asg, size: 2 }
    - { role: ecs_service }
  tasks:
