- hosts: localhost
  gather_facts: false
  tasks:
  - name: Create notejam EC2 key
    ec2_key:
      name: notejam_ec2_key
    register: ec2_key
  - name: save private key
    copy:
      content: "{{ ec2_key.key.private_key }}"
      dest: "~/.ssh/notejam-private.pem"
      mode: 0600
    when: ec2_key.changed
  - name: Create jenkins security group
    ec2_group:
      name: jenkins
      description: Group to use for jenkins CI/CD
      rules:
      - proto: tcp
        from_port: 8080
        to_port: 8080
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
  - name: Create EC2 instance for jenkins
    ec2:
      key_name: notejam_ec2_key
      instance_type: t2.micro
      image: ami-965e6bf3
      wait: yes
      group: jenkins
      exact_count: 1
      count_tag: type
      assign_public_ip: no
      instance_tags:
        type: jenkins
    register: ec2
  - name: Created jenkins instances public ip
    debug: var={{ item }}
    with_items:  ec2.tagged_instances[0].public_ip
  - name: Add jenkins instance to inventory
    add_host:
      name:  "{{ ec2.tagged_instances[0].public_ip }}"
      group: jenkins

- hosts: jenkins
  become_method: sudo
  gather_facts: false
  pre_tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
      become: true
    - setup: # aka gather_facts
  tasks:
    - name: Add apt-key for jenkins repository
      become: true
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
        state: present
    - name: Add jenkins apt repository
      become: true
      apt_repository:
        repo: deb-src http://pkg.jenkins.io/debian-stable binary
        state: present
    - name: Update apt-get cache
      become: true
      apt: cache_valid_time=7200 update_cache=true
    - name: Install required packages
        become: true
        apt: name={{item}} state=present
        with_items:
          - openjdk-8-jre-headless
          - jenkins

