---
  - name: Create staging instances lunch configuration
    ec2_lc:
      name: "{{ app_name }}_lc"
      key_name: notejam_ec2_key
      assign_public_ip: yes
      security_groups: ["{{ app_name }}"]
      image_id: "{{ ami_ecs_optimized }}"
      instance_type: "{{ instance_type }}"
      instance_profile_name: "ecsInstanceRole"
      user_data: |
        #!/bin/bash
        yum install -y awslogs
        chkconfig awslogs on
        service awslogs start
        echo ECS_CLUSTER={{ ecs_cluster_name }} >> /etc/ecs/ecs.config
        echo ECS_ENABLE_TASK_IAM_ROLE=true >> /etc/ecs/ecs.config

  - name: "Lunch asg ec2 for {{ app_name }}"
    ec2_asg:
      name: "{{ app_name }}_asg"
      launch_config_name: "{{ app_name }}_lc"
      health_check_period: 60
      health_check_type: ELB
      min_size: "{{ size }}"
      max_size: "{{ size }}"
      vpc_zone_identifier: "{{ vpc_subnets_ids}}"
      desired_capacity: "{{ size }}"
      wait_for_instances: true
      tags: [{ecs_cluster: "{{ ecs_cluster_name }}"}]

