---
subnets: [
    {cidr: 172.23.0.0/24, region: us-east-2, az: us-east-2a},
    {cidr: 172.23.1.0/24, region: us-east-2, az: us-east-2b}]
app_name: "notejam-staging"
vpc_net: 172.23.0.0/16
backup_retention: 1
instance_type: t2.micro
container_memory: 400

